### ISSUE TITLE
Linq2Db4iSeries - Missing from NuGet

### ISSUE THREAD

**Issue by mkchmiel** [LinqToDB4iSeries/Linq2DB4iSeries#1]
Hello,

I was trying to download this but have been unable to find it within NuGet, was searching for Linq2Db4iSeries. I did find Linq2Db but not this one, any suggestions on how to get it? I did try building the project after pulling in the repo but it came up with a few errors which stopped compilation from completeing. 

Thanks for the help,
regards Mark.

**Comment by RoyC-Retail-Assist** [comment]
I haven't published it as a package into NuGet as it has dependencies on the IBM.Data.DB2.iSeries that need to be downloaded from IBM.

If you have ISeries Access for Windows installed on your machine then it should compile.  What errors are you getting when trying to compile?

**Comment by mkchmiel** [comment]
Didnt get a chance to look into it till now, looks like nuget package restore errors prevented it from compiling. 

Error	14	NuGet Package restore failed for project LinqToDB.DataProvider.DB2iSeries: Unable to find version '1.7.6-rc246' of package 'linq2db'..		0	0	

Does it have to be dependent on a release candadite of Link2DB? I can try to make it work locally with the currently release version, but not sure how significant the changes were.

**Comment by RoyC-Retail-Assist** [comment]
The dependency should be on V1.7.6 not the pre-release version.  I've pushed the change so if you get the latest it will hopefully build.

**Comment by mkchmiel** [comment]
Thanks.

**Comment by mkchmiel** [comment]
I am pretty close now, just getting an "Error	4	The name '_endLine' does not exist in the current context	C:\Users\mchmiel\Downloads\Linq2DB4iSeries-master (1)\Linq2DB4iSeries-master\ISeriesProvider\DB2iSeriesSqlBuilder.cs	219	11	LinqToDB.DataProvider.DB2iSeries".

Only one reference to it in the entire project in the entire project. Any thoughts, I have a feeling I might be missing something here.

**Comment by arbh89** [comment]
I am having the same issue trying to compile.

Can you use the package https://www.nuget.org/packages/IBM.Data.DB2.iSeries/ as dependency?

**Comment by RoyC-Retail-Assist** [comment]
_endline is a protected variable in BasicSqlBuilder,  I would suggest that you try deleting the bin folder in the project and trying to compile again.  It all compiles OK on my machine at work but it is possible there is something that I have missed.  If it still doesn't work for you I'll try it on a different machine at home tonight.

The IBM.Data.DB2.iSeries could be used however all it would do is allow the solution to compile.  There are numerous com objects required for the actual ADO.Net connection to the ISeries and these can only (to the best of my knowledge) be correctly installed from the official IBM setup.  If you know of some other way of getting the full setup installed I'l be happy to consider a pull request with them.

**Comment by mkchmiel** [comment]
Sadly cleaning the bin folder and solution, and rebuilding had not resolved my issue. To me it looks like _endLine is not defined in LinqToDB.SqlProvider.BasicSqlBuilder. I do see that EndLine is defined as an array of characters but _endLine was not defined any where else in the solution.

Thank you for looking into this for us Roy, I would really want to see if this would resolve some of my SQL headaches with IBM iSeries. We have 11 Schemas with the same tables and columns and cannot use ADO.NET as an ORM :-\ ...

**Comment by arbh89** [comment]
Using linq2db version 1.7.6 the variable is called EndLine.

![image](https://cloud.githubusercontent.com/assets/6992258/25621157/b5d362e4-2f0d-11e7-8f4e-5e476f735cbb.png)

So, replacing _endLine to EndLine do the trick.

![image](https://cloud.githubusercontent.com/assets/6992258/25621191/d78d0020-2f0d-11e7-9a69-d13458f4fe8b.png)

**Comment by mkchmiel** [comment]
Good call man, successfully built on my side. Roy I am closing this as we have our work around with the solution. Thanks arbh89, good call.

**Comment by RoyC-Retail-Assist** [comment]
Reopening pending codefix

I think I have cached package somewhere in my development system.  I'll fix the issue and then re-run the unit tests just to validate.

I'll look to publish a Nuget package at some point if that would be of use.

Thanks for your input gents.

**Comment by arbh89** [comment]
@RoyC-Retail-Assist, you have updated the linq2db package in main project but tests projects are referencing version 1.7.6-rc246, this need to be updated in order to compile.

**Comment by RoyC-Retail-Assist** [comment]
Fixed in commit fc00905
