### ISSUE TITLE
LoadExpressions - Guid expression is set using ProviderName instead of MapGuidAsString flag

### ISSUE THREAD

**Issue by nsarris** [LinqToDB4iSeries/Linq2DB4iSeries#13]
I am not sure this is an actual issue but I've noticed so I'm posting it here:

In DB2iSeriesExpressions.LoadExpressions there is a map that looks like the map from guid to char16

It is applied by providerName:

if (providerName == DB2iSeriesProviderName.DB2)

Shouldn't it check the MapGuidAsString flag?

**Comment by RoyC-Retail-Assist** [comment]
Good spot.  I'll fix it and also remove the Expression class as it is only used in one place.

**Comment by RoyC-Retail-Assist** [comment]
Fixed in v2.2.0.3
