### ISSUE TITLE
Min()/Max() on empty table

### ISSUE THREAD

**Issue by spudcz** [LinqToDB4iSeries/Linq2DB4iSeries#18]
Hi,
when you make a query to retrieve min/max ID from empty table it throws exception even when you use method DefaultIfEmpty()

**exception**
> Function Max returns non-nullable value, but result is NULL. Use nullable version of the function instead.

**model:**
```
[Table(Name = "Table")]
public class Table {
  [Column(Name = "Id", DataType = DataType.Int64)]
  public long Id { get; set; }
  [Column(Name = "Something", DataType = DataType.VarChar)]
  public string Something { get; set; }
}
```

**LINQ query:**
```
using (var conn = new DbConnection() {
  var maxId = conn.Tables.Select(x => x.Id).DefaultIfEmpty(0).Max();
}
```

**SQL generated:**
`SELECT Max(t1.Id) FROM Table t1`

**Expected SQL:**
`SELECT Ifnull(Max(t1.Id), 0) FROM Table t1`

**Comment by RoyC-Retail-Assist** [comment]
Id is not nullable in your class but what is being returned is DBNull.

Try

`conn.Tables.Max<Table, int?>(f => f.Id).GetValueOrDefault(0);`

**Comment by spudcz** [comment]
Thanks, it works! 

The method DefaultIfEmpty() was not used correctly by me or it's not just implemented by your library?

**Comment by RoyC-Retail-Assist** [comment]
If Id was int? your construct would have worked but null cannot be mapped back to a non nullable field.

This is not provider specific.
