### ISSUE TITLE
Nuget package for latest version

### ISSUE THREAD

**Issue by tb-mtg** [LinqToDB4iSeries/Linq2DB4iSeries#19]
Are you able to please provide a Nuget package for the latest version?

I noticed that there is only a prerelease Nuget package for version [2.0.0-rc1](https://www.nuget.org/packages/linq2db4iSeries/2.0.0-rc1).  

Also, currently is the latest version [2.2](https://github.com/LinqToDB4iSeries/Linq2DB4iSeries/tree/V2.2) as shown in branches menu, or [1.10.2](https://github.com/LinqToDB4iSeries/Linq2DB4iSeries/releases/tag/v1.10.2) as shown on releases page)?

Lastly I just want to say excellent work on this project!

**Comment by RoyC-Retail-Assist** [comment]
I'm doing alittle bit of tidying at the moment. One thing on my list is to prepare a package and update the Wiki appropriately.  

I hope to be able to provide a package some time next week but am waiting for permisson from my employer to be able to publish the binaries.

The latest version is the 2.2 branch which I will merge into main.  I'f you want to create you own package from this then version it as 2.2.0 as I will be publishing 2.2.0.3 (the other revision versions are being used in house and I've just completed Cte support this evening)

**Comment by RoyC-Retail-Assist** [comment]
v2.2.0.3 released and package on NuGet
