### ISSUE TITLE
Switch between different Collection/Library

### ISSUE THREAD

**Issue by mkchmiel** [LinqToDB4iSeries/Linq2DB4iSeries#2]
Hello,

How can I switch between collection/libraries? I am dealing with a data base that has 11 which have identical table structures and want to be able to switch between them dynamically.

**Comment by RoyC-Retail-Assist** [comment]
Use the schemaname method db.GetTable<TABLE>().SchemaName(SCHEMANAME) to get the table instance from the specified schema.

**Comment by mkchmiel** [comment]
Thanks Roy,

I wasnt able to find SchemaName as a function, am I missing something here?

**Comment by RoyC-Retail-Assist** [comment]
It is part of the Linq2DB functionality.  You will need to add **`use Linq2DB;`** and then it should show up in Intellisense.

I added a test yesterday https://github.com/LinqToDB4iSeries/Linq2DB4iSeries/blob/master/Tests/Linq/Linq/ExtensionTests.cs

and it found my test schema but didn't find the "wibble" schema.

**Comment by mkchmiel** [comment]
This is awesome Roy, this worked for me :). Much appreciated.
