### ISSUE TITLE
DB2Connect support

### ISSUE THREAD

**Issue by nsarris** [LinqToDB4iSeries/Linq2DB4iSeries#22]
We've switched from iDB2 to DB2Connect which uses the IBM.Data.DB2 client with proper async support, EF 6 support, .net core and EF.core support etc etc. We've seen vastly better performance, better distributed transaction support etc. It's a bit expensive but even IBM advised us to use it over IBM.Data.DB2.iSeries.

To achieve this i've ported the DataProvider / Factory / ProviderName / Tools and Types classes from the standard Linq2db DB2 provider and used them with your SQL generation code with minimal changes to the original source code. This has been working flawlessly for us for the past few months. But at this point I think we can discuss perhaphs merging the DB2Connect provider in Linq2DB4iSeries if you agree. 
Or we rearrange the solution to a common project with two separate providers. 

P.S. Along with the DB2Connect provider I implemented a provider for HIS (Hist Integration Server - Microsoft's provider for i Series). I abandoned because it was insanely slow in performance but I have it available non the less.

**Comment by RoyC-Retail-Assist** [comment]
We looked at DB2Connect but the cost was prohibitive at the time. 

I'm not against looking into what we could do around this but my initial concern is how/who would be able to run the unit tests.  We do not have DB2Connect in house and, unless there was some really cheap and easy way to get it set up I'm unlikely to be able to persuade anyone here to pay to install it therefore I wouldn't be able to test against it.

Is DB2Conect just client side or does it require a server installed on the iSeries?  

Can you create a PR for review so that I can see what you have done 

I'm on vacation next week so won't be able to respond to anything after Friday until the 1st Oct.

**Comment by nsarris** [comment]
It's all client side, all it needs is a .lic file to be registered on each client machine along with the Data Server Client installation (I'll provide detail instructions)

IBM gave us a trial license file to run our initial tests (which never expired, I still use it on my dev and uat machines). I don't see a reason why they wouldn't provide one to you as well if you tell them what you do.

Besides that I can run the tests here if you help me with the setup. I'll create the PR

**Comment by RoyC-Retail-Assist** [comment]
I've had a look at your PR #23 and it's difficult to see where the differences are to the current provider.   

Having a completely separate provider means that there is a lot of duplicated code and my initial thought would to try to roll it into a single provider if possible.  This would also need to be based off the current version as there are changes I made to the provider detector to enable use in LinqPad (and just because it was better).

**Comment by nsarris** [comment]
If you are ok with it I will rewrite it as a single provider with an option for the underlying ADO.net provider.

**Comment by RoyC-Retail-Assist** [comment]
If you can do that then I don't see why we shouldn't include it.  

If you create a PR for the work we can take things from there.

I've got our iSeries guys looking into getting me an evaluation licence so fingers crossed I can get a test system working with it.

**Comment by nsarris** [comment]
Ok so I've got everything ready and all the tests are passing (except one of the merge tests that fails on your master branch at the moment and one of the truncate tests)

The only major change I took the liberty of doing was with the Types infrastrcuture. The original linq2db code from DB2 was a statics mess. All the TypeCreators were staticly instantiated without the type they create, which was "plugged" in at OnConnectionType created, which run for each provider instance. The ConnectionType instance itself was created via a compiled constructor expression, and the type was aquired via a call to Type.GetType using the assembly and connectionType name from DB2Tools. I chose to fully rewrite this promoting the TypeCreators to TypeDescriptors that held all the related information for each DB2 or iDB2 type. This simplified everything and reduced a lot of boilerplate code.

The other changes are mostly to accomodate the different implentations between the two ADO providers.  The current version is here: https://github.com/nsarris/Linq2DB4iSeries/tree/DB2ConnectIntegration

If you want me to create a PR I suggest you create a branch on your repo so I can send the PR there and not on master. Let me know what you think.

**Comment by RoyC-Retail-Assist** [comment]
I've created a DB2Connect branch that you can PR to.

**Comment by RoyC-Retail-Assist** [comment]
Apologies for not responding earlier.  We are at a very busy time at the moment.


The PR that you submitted has too many changes for me to be confident that there will not be regression issues from it.  The refactoring of how the providers are instantiated also significantly differs, code wise, from the "standard" Linq2DB providers which could mean that any changes that they make in that area may be difficult to incorporate in the future.  I can fully uunderstand why you did the refactoring but it's a step to far at the moment.


Is there something simple that could be done to add the provider for now?

**Comment by nsarris** [comment]
I could create a seperate project in the solution that is dependent on the original and provides a different DataProvider alltogether (this was my initial approach, but in the same project)

This will mostly leave the original project intact and simply inherit the common parts (which is mostly the sql generation/optimizer code and schema provider)

How does that sound?

**Comment by RoyC-Retail-Assist** [comment]
That sound a better approach for the moment.  It may want a little bit of work around a common provider detector but that might be fairly simple.


Does DB2Connect require anything extra installing or licensing on the iSeries or is it just client licencing?

**Comment by nsarris** [comment]
Ok I'll try to find some time to adjust. Is it OK if I keep the new way of handling types in the new project?

There are two possible licensing schemes. One is per client and the other is an unlimeted license. The first one installed on each client machine. The second can be installed on the clients or on the i series itself.

The trial we had here was the second option but the host engineers didn't want to set it up on the test host environment so we installed it on the clients. The end license we bought was the client one so I haven't really seen the unlimited lisense in action on the host

Resources:

DB2Connect lices Types: http://www-01.ibm.com/support/docview.wss?uid=swg21626371
Activate DB2Connect Unlimted for i Series on host: https://www.ibm.com/support/knowledgecenter/en/SSEPGG_11.1.0/com.ibm.db2.luw.licensing.doc/doc/t0057375.html

**Comment by RoyC-Retail-Assist** [comment]
I'd really like to keep the changes to the minimum at the moment.  The closer that we mirror the way things are done in Linq2DB the easier it is to maintain.  If we diverge too far then any refactoring that they might do in the future will be far harder to integrate.

**Comment by nsarris** [comment]
I'd like to point it that the static mess I tried to improve is only used in the DB2 dataprovider and is not a common practice within linq2db itself. Most of the other drivers use static references on inline reflection. I suspect that if they try to change anything they should move away from that pattern in DB2. I'd be happy to provide them a PR on that.

Since it passes all tests pass (which was the purpose that infrastructure was primarily built for anyway) I don't see a major problem with keeping it there on the new provider. It won't break anything on the existing provider (so no regression issues) and I'd be a great change to see it working properly.

So I insist on keeping it on the new provider, but it's your call.
