### ISSUE TITLE
DbProviderFactory support

### ISSUE THREAD

**Issue by MaceWindu** [LinqToDB4iSeries/Linq2DB4iSeries#29]
Adding issue for this [comment](https://github.com/linq2db/linq2db/pull/1466#issuecomment-447580994)

In linq2db 2.6 we added built-in support for DbProviderFactory in DynamicDataProviderBase (https://github.com/linq2db/linq2db/pull/1410)

This changes default provider assembly discovery procedure to fallback to DbProviderFactory mechanisms when provider assembly is not found in application folder. In other words it:
- adds support for scenarios where users don't need to include/reference provider assembly in to his project
- solves compatibility issues when managed assembly shipped with linq2db and then it doesn't work properly, because it's version doesn't match installed provider version.

All you need to do is to add following override to provider class to tell linq2db which provider factory to use:
```cs
public override string DbFactoryProviderName => "IBM.Data.DB2.iSeries";
```
looks like `IBM.Data.DB2.iSeries` is a correct factory name. At least IBM use it [here](https://www-01.ibm.com/support/docview.wss?uid=nas8N1012022) (invariant attribute)

**Comment by RoyC-Retail-Assist** [comment]
Added in v2.6.1.

@MaceWindu let me know when the necessary changes have been made to the LinqPad provider and I will test that it works.
