### ISSUE TITLE
CWBDC.dll missing

### ISSUE THREAD

**Issue by mattmcnabb** [LinqToDB4iSeries/Linq2DB4iSeries#31]
I'm not able to use this library on a machine with the iAccess Client Solution installed. Any attempts to use it result in the error "CWBDC.dll is missing." Are you aware of the particular dependencies on the iAccess client application so that I might include the dlls in my project?

Thanks!

**Comment by RoyC-Retail-Assist** [comment]
The only direct dependency is to IBM.Data.DB2.iSeries.dll however that almost certainly calls CWBDC.dll which is a COM component.

Are you targeting .Net Framework?  I seem to remember getting similar issues when investigating .Net core.

**Comment by mattmcnabb** [comment]
I'm targeting .Net Framework. I'll keep poking around to see if I can figure out what is required. Thanks!

**Comment by RoyC-Retail-Assist** [comment]
I'm guessing that there is something wrong with the iAccess install. I'd suggest:

1. Check that you can run an SQL Query in iNaviagtor.  
2. Write a quick console app to create an iDB2Connection and iDB2Command then run the command.  (this is what the provider does under the hood).

If/when you do find the solution can you update this issue with the resolution as it may help others.

**Comment by mattmcnabb** [comment]
@RoyC-Retail-Assist I was finally able to resolve this. I simply had our support team install the .Net Data provider package from IBM and I was able to make basic calls. Thanks!

**Comment by bharathkumarvasudevan** [comment]
Is there any way to load/embedd CWBDC.dll in the code itself?
