### ISSUE TITLE
Linq2Db release Version 3

### ISSUE THREAD

**Issue by travbeamo** [LinqToDB4iSeries/Linq2DB4iSeries#41]
Version 3 is out now, do you plan to update this excellent repository?

https://github.com/linq2db/linq2db/wiki/Release-Notes-3.0.0

_Originally posted by @travbeamo in https://github.com/LinqToDB4iSeries/Linq2DB4iSeries/issues/9#issuecomment-659755884_

**Comment by RoyChase** [comment]
After changing jobs I no longer have access to an ISeries to test against.  I passed over ownership of this to @nsarris so maybe he will be able to answer.

**Comment by travbeamo** [comment]
@nsarris Are there any plans to update this?

**Comment by nsarris** [comment]
Yes we have plans to update it in the coming weeks

**Comment by nsarris** [comment]
Update, we are at RC1, waiting for linq2db to release 3.2 as I commited a couple of bug fixes for this provider to work. 

@travbeamo

**Comment by nsarris** [comment]
v3.1.5 has been released with oledb and odbc support. Please try it and let us know of any issues.
