### ISSUE TITLE
Support for DB2iSeries using Odbc and/or OleDb

### ISSUE THREAD

**Issue by travbeamo** [LinqToDB4iSeries/Linq2DB4iSeries#42]
See issue raised here for details: https://github.com/linq2db/linq2db/issues/2473

**Comment by nsarris** [comment]
@travbeamo v3.1.5 has been released with oledb and odbc support. Please try it and let us know of any issues.

**Comment by travbeamo** [comment]
Great job, I’ve got a busy few days at the moment but will test it and let you know. 

Also I have 3 semi-working versions based on DataProviderBase (rather than the DynamicDataProviderBase) for OdbcConnection, OleDbConnection & iDB2Connection that I will compare the code to.

**Comment by nsarris** [comment]
I think you mentioned on the linq2db thread that you're on V5.4 and this provider supports V7.1 upwards. There could be a few breadking issues on this version (e.g. upserts use Merge statement that was introduced with 7.1).

 You can try running the tests on V5.4 and see what fails.
