### ISSUE TITLE
Output parameters with ODBC provider

### ISSUE THREAD

**Issue by spudcz** [LinqToDB4iSeries/Linq2DB4iSeries#63]
When I call stored procedure using ODBC provider, all parameters in SQL query are named as question mark. If I want to retrieve value from output parameters after calling method ExecuteProc() then in all output parameters there is the value from the first parameter added to collection.
It is probably looking for parameter by name and then it takes the first one ... as all of the parameters are named as '?' it doesn't returns valid value.

In this sample I got in parameters parRoleId, parTsOut and parInsInfo value from input parameter called OBJECT
```
    public object? GetInsuranceInfoFromCalculation(int objectNumber, string insuranceCode)
    {
        // output parameters
        var parRoleId = DataParameter.Char("ROLEID", "");
        parRoleId.Size = 10;
        parRoleId.Direction = ParameterDirection.Output;

        var parTsOut = DataParameter.Char("TSOUT", "");
        parTsOut.Size = 26;
        parTsOut.Direction = ParameterDirection.Output;

        var parInsInfo = DataParameter.Char("INSINFO1", "");
        parInsInfo.Size = 500;
        parInsInfo.Direction = ParameterDirection.Output;

        // call
        this.ExecuteProc(
            "CALL MyLib.GetInsuranceInfo (?, ?, ?, ?, ?, ?, ?)",
            DataParameter.Char("OBJECT", $"{objectNumber}"), 
            DataParameter.Char("INSCODE", insuranceCode), 
            DataParameter.Char("VALIDAT", "9999-01-01"), 
            DataParameter.Char("TSIN", $"{DateTime.Today:yyyy-MM-dd HH:mm:ss.ffffff}"), 
            parRoleId, 
            parTsOut, 
            parInsInfo
        );

        return parInsInfo.Value;
    }
```

**Comment by nsarris** [comment]
Hi @spudcz and sorry for the delayed response.

I checked this out and it is an intristic Linq2DB behaviour that is not overridable. I guess the out of the box providers don't support a case where parameter marker names are not supported and stored procedures are.

The problem boils down to the fact that command state is stored as System.Data.DbParameter, so there is no way to store the actual name and marker name(?) seperatly. I had to replace the original parameter names with the marker symbol. Later on Lin2DB tries to rebind the outpout value from the dbparameter to the original parameter. As the names have been replaced there is no way to map back.

There are two ways to fix this and they both require a PR to Linq2DB. One is to add a provider flag to explicitly set wether a provider supports parameter names, and if not have CommandInfo,RebindParameters fallback to sequencial mapping. The other is have RebindParameters be intercepted by the DataProvider so provider developers can handle this senario on their own.

I will try to find some time to check this out with them, in the mean time you could raise an issue over there.

**Comment by spudcz** [comment]
Hi, Nikos,

thank you for your reply. I had to solve the problem earlier, so I switched
to using ADO.NET for this particular call to the mentioned stored procedure
and it worked fine. Fortunately, this was the only time I had to work with
a stored procedure using multiple output parameters :-).


ne 18. 9. 2022 v 10:48 odesílatel Nikos Sarris ***@***.***>
napsal:

**Comment by nsarris** [comment]
@spudcz I took a closer look and I found out the reason to rename those parameters back then was addressed by Linq2db a while back, so I took some time to fix the issue. It has been releaesd as v4.0.1.1
