### ISSUE TITLE
Update needed for .net core

### ISSUE THREAD

**Issue by MicahKimel** [LinqToDB4iSeries/Linq2DB4iSeries#68]
It would be super awesome to update this package so that it can work in C# .net core.

**Comment by nsarris** [comment]
@MicahKimel the package is working with core since version 3, what problems are you facing?

**Comment by MicahKimel** [comment]
@nsarris Oh sweet I didn't realize that, thanks! For some reason my connection string that I used in framework now gives `["Invalid Argument" exception message on IBM.Data.DB2.DB2Connection .open method](https://stackoverflow.com/questions/9434241/invalid-argument-exception-message-on-ibm-data-db2-db2connection-open-method)`

I've messed around with it some and changed my connection string to this format
Database=DB;Server=SERVER:PORT;UID=USER;Pwd=PASS;LibraryList=LIBRARY;PersistSecurityInfo=True;

But I get this error
 `IBM.Data.Db2.DB2Exception (0x80004005): ERROR [42968] [IBM] SQL1598N  An attempt to connect to the database server failed because of a licensing problem.  SQLSTATE=42968`

So this package is working great in .net core! I just need to figure out how to get the license fixed I think.

**Comment by nsarris** [comment]
Bare in mind that DB2 / DB2Connect provider requires a (very expensive) license, that is why you are getting this message.

Please check out the wiki here for connection string examples and details on the 4 supported providers.

https://github.com/LinqToDB4iSeries/Linq2DB4iSeries/wiki

**Comment by MicahKimel** [comment]
Oh dang, thank you!!!!
