### ISSUE TITLE
LinqToDB 5 migration

### ISSUE THREAD

**Issue by MaceWindu** [LinqToDB4iSeries/Linq2DB4iSeries#69]
@nsarris

We just released [5.0.0-preview.2 release](https://github.com/linq2db/linq2db/releases/tag/v5.0.0-preview.2) and it would be nice if you can check for any migration issues before final release (expected in 2-3 weeks)

**Comment by nsarris** [comment]
@MaceWindu #71 , all tests are passing, ping me when release is merged so I can run test against it.

**Comment by nsarris** [comment]
@MaceWindu v5 released. In a future patchcould you make internals visible to LinqToDB.DataProvider.DB2iSeries. This would allow removing some code copied over and allow usage of internal tools.

**Comment by MaceWindu** [comment]
I'm not a big fan of IVT. Could you provide a list of APIs you need so we will make them public?

**Comment by nsarris** [comment]
Well nothing specific, was just an idea, I guess at this point I only really need Method LinqToDB.DataProvider.DB2.DB2BulkCopy.ProviderSpecificCopyImpl<T> , but I can live with copying it over when it changes.
