### ISSUE TITLE
"CCSID <integer>" is invalid with Db2Connect LUW

### ISSUE THREAD

**Issue by omarpiani** [LinqToDB4iSeries/Linq2DB4iSeries#72]
Hi, I'm trying a working  code (connected ODBC vs AS400) in a docker instance of DB2 LUW and I get this error:

`ERROR [56031] [IBM][DB2/LINUXX8664] SQL0622N  The clause "CCSID <integer>" is invalid for this database.`

Seems a problem with parameters type/cast.

This will throw the exception:

`var article = conn.FromSql<Article>("SELECT * FROM ARTICLES t WHERE t.CODART = {0}", "XXXX").SingleOrDefault();`

where CODART is varchar 

Adding apices on parameter will fix: `"SELECT * FROM ARTICLES t WHERE t.CODART = '{0}'"`

I cannot find a walkthrough for Insert() from the poco object

I used previously docker LUW with DB2Connect with EFCore but that cannot connect to AS400

I moved to that ODBC but now PUB400.COM seems down forever :( what a pain work with IBM

Thank's for all you did with this lib!

**Comment by nsarris** [comment]
Hi @omarpiani 

DB2 LUW should be used with the DB2 provider included with linq2db, that's a different provider than the one in this repo, so naturally using the DB2i provider against a DB2 LUW database will produce all sorts of errors.

DB2Connect for i series requires a very expensive commercial license, check the wiki for supported provider info.

For Insert usage go to https://github.com/linq2db/ they have lot's of usage examples.

PUB400.com is up right now if you need to test against that. If you still get an issue let me know.

**Comment by omarpiani** [comment]
yee, I managed to fix my program with pub400 that is back online. 

btw before that I was using Db2Connect with IBM.EntityFrameworkCore and LUW and was working

Thanks for all!
