### ISSUE TITLE
Avoid CASTing of parameters

### ISSUE THREAD

**Issue by mordio** [LinqToDB4iSeries/Linq2DB4iSeries#76]
_Originally posted by @nsarris in https://github.com/LinqToDB4iSeries/Linq2DB4iSeries/issues/44#issuecomment-720123280_:
> Casting as a quirk of i series, it requires casting parameters in most places (there is an article on IBM on that). If you just add an uncasted parameter it throws an exception. Instead of trying to determine where a cast is needed, I decided cast all parameters, and specifically to upcast all text and numeric parameters to their largest possible version (e.g. text to clob, unicode text to nclob, numbers to decimal(60,30)) so that the value can fit.

Is there any way to avoid or override this behavior? Like with an SqlExtension or something. The reason I am asking is because the casting `CAST(? AS DBCLOB CCSID 1200)`  misguides the SQL optimizer to not use indexes and do a **table scan** instead. As you can imagine the performance impact is horrible.

Unfortunately I cannot change the database schema. The supplier is using a combined key of character columns not a single identity column. I am only querying the data.

**Comment by mordio** [comment]
I found a workaround. The table scan can be avoided by annotating the columns in the model with the correct `DataType`:

```cs
using LinqToDB;
using LinqToDB.Mapping;

namespace project.Models
{
    [Table(Name = "INVHEAD")]
    public class InvoiceHeader
    {
        [Column(Name = "SALREG"), NotNull]
        [DataType(DataType.Char)]
        public string SalesRegion { get; set; } = "";
        
        [Column(Name = "DOCFLAG"), NotNull]
        [DataType(DataType.Char)]
        public string DocumentType { get; set; } = "";
        
        [Column(Name = "INVNUM"), NotNull]
        [DataType(DataType.Char)]
        public string InvoiceNumber { get; set; } = "";
    }
}
```
This causes the parameters to be cast as `CAST(? AS CLOB)` which the optimizer recognizes as unnecessary and therefore the indexes to be used.

Please keep up the good work!
Kudos!

**Comment by travbeamo** [comment]
I still don’t see the need for a cast at all. 

I have been able to just use a question mark without a cast using the OdbcDataConnection without any issues.
